### ISSUE TITLE
Showing new DejalActivityView during remove animation of the old one, prevents the new one from appearing

### ISSUE THREAD

**Issue by grzegorzkrukowski** [Dejal/DejalActivityView#16]
Because you are using singleton approach there is a problem when you quickly show DejalActivityView one after another (when old one is still animating to remove itself).

You are partially taking care of existing views during init:

`if (dejalActivityView)
        [self removeView];`

But the problem is that if there is removal animation still in progress, the completion selector will still be executed.

`- (void)removeAnimationDidStop:(NSString *)animationID finished:(NSNumber *)finished context:(void *)context` 

In that case `finished` parameter will be @(0) - since animation was cancelled, by removing a view from a superView. Without checking for that value this completion selector removes a new instance of a popup which you wanted to be visible.

You should be checking for the `finished` parameter value to prevent that.
Alternative will be checking:
`if(dejalActivityView == self)` in that method

**Comment by Dejal** [comment]
Thanks for the fix.
