### ISSUE TITLE
is there a chunk of dead code in  DejalActivityView.m ?

### ISSUE THREAD

**Issue by AEDWIP** [Dejal/DejalActivityView#18]
Hi David

DejalActivityView is really useful. It looks like we are using a very old version. I.E. pre github. I was going through the code. I wanted to fix a couple of deprecated font related warnings. 

seem like you use a style of code I am not familiar with. 

prototype with a semi colen
chuck of code?

What does this do?

 I noticed around line 300 what looks like a prototype and a chunk of code. I wonder if this dead code? I set a break point. It never seems to execute

```
- (void)layoutSubviews;
{
    self.frame = [self enclosingFrame];
    
```
    
I noticed something similar around line  569. a prototype and chunk of code. I know this chunk executes. 

```
- (void)layoutSubviews;
{
    // If we're animating a transform, don't lay out now, as can't use the frame property when transforming:
    if (!CGAffineTransformIsIdentity(self.borderView.transform))
        return;
    
    self.frame = [self enclosingFrame];
    
    CGSize maxSize = CGSizeMake(260, 400);
    
    // https://stackoverflow.com/questions/19145078/ios-7-sizewithattributes-replacement-for-sizewithfontconstrainedtosize
//    CGSize textSize = [self.activityLabel.text sizeWithFont:
//                       [UIFont boldSystemFontOfSize:[UIFont systemFontSize]]
//                                          constrainedToSize:maxSize
//                                              lineBreakMode:self.activityLabel.lineBreakMode];
    //SCILog(@"deprecated textSiz: h:%f w:%f", textSize.height, textSize.width)
    NSDictionary *attributes = @{NSFontAttributeName: [UIFont boldSystemFontOfSize:[UIFont systemFontSize]]};
    CGRect rect = [self.activityLabel.text boundingRectWithSize:maxSize
                                                        options:NSStringDrawingUsesLineFragmentOrigin
                                                     attributes:attributes
                                                        context:nil];
    CGSize textSize = rect.size;
    //SCILog(@"deprecated textSiz: h:%f w:%f", textSize.height, textSize.width)

```

kind regards

Andy

**Comment by Dejal** [comment]
The semicolon after the method name makes it easier to copy the line to the header file. The semicolon is optional, and is ignored. It isn’t dead code.

**Comment by AEDWIP** [comment]
Hi Dejal

You have two functions with exact same signature. I suspect the compiler / linker only sees one. In my case I know the last one is executed. It is not clear when the first one would be executed. 

You might consider implementing using a more modern style based on categories
https://developer.apple.com/library/content/documentation/General/Conceptual/DevPedia-CocoaCore/Category.html

One advantage of this style is the compiler will generated an "error: duplicate declaration of method" error.

```
//
//  SpotifyAuthController.m
// 

#import "CacheHelper.h"
#import "SCIMediaItem.h"

@interface CacheHelper(Private)
+ (void) copySampleSong:(FileInfoData *)audioFileData 
                FromAppBundleWithDelegate:(NSObject<CacheHelperDelegate> *)delegate 
                withCallbackData:(void *)callbackData ;

- (void) play;

@property (nonatomic, strong) ImportSpotifyCoreAudioController *iscac;

@end


@implementation CacheHelper

@synthesize iscac;

///////////////////////////////////////////////////////////////////////////////
+ (void) copySampleSong:(FileInfoData *)audioFileData 
        FromAppBundleWithDelegate:(NSObject<CacheHelperDelegate> *)delegate 
        withCallbackData:(void *)callbackData {

 ...

}

- (void) play {

  ...

}

@end
```

**Comment by Dejal** [comment]
The first is in a local header for private methods.  Did you not notice the `@interface`?  This used to be required to be able to call them, though nowadays the compiler can find methods within the same file without it.

**Comment by AEDWIP** [comment]
Hi Dejal

I really like your work. You have two functions with the same signature. I is not clear which version will be use when. I am just trying to encourage you to make your code more valuable by making it easier to understand and maintain. You know https://en.wikipedia.org/wiki/Occam%27s_razor. Try and keep things simple whenever possible

Kind Regards

Andy

**Comment by drallgood** [comment]
@AEDWIP I think you didn't read that file carefully enough. There are multiple classes in the same file, hence the duplicate methods.
I agree, though, that this is bad style and should be split into separate files.
